In [1]:
# import all necessary packages
import pandas as pd
import numpy as np
import json
import datetime
import seaborn as sns
import matplotlib as mlp
import matplotlib.pyplot as plt

from haversine import haversine
#from datetime import datetime

In [2]:
# import datasets: every month individually

df_jan = pd.read_csv("data/Taxi_Trips.csv")
df_feb = pd.read_csv("data/Taxi_Trips-2.csv")
df_mar = pd.read_csv("data/Taxi_Trips-3.csv")
df_apr = pd.read_csv("data/Taxi_Trips-4.csv")
df_may = pd.read_csv("data/Taxi_Trips-5.csv")
df_jun = pd.read_csv("data/Taxi_Trips-6.csv")
df_jul = pd.read_csv("data/Taxi_Trips-7.csv")
df_aug = pd.read_csv("data/Taxi_Trips-8.csv")
df_sept = pd.read_csv("data/Taxi_Trips-9.csv")
df_oct = pd.read_csv("data/Taxi_Trips-10.csv")
df_nov = pd.read_csv("data/Taxi_Trips-11.csv")
df_dec = pd.read_csv("data/Taxi_Trips-12.csv")

In [3]:
# combining the dataframes to one (for the whole year)

df_chicago = pd.concat([df_jan,df_feb,df_mar,df_apr,df_may,df_jun,df_jul,df_aug,df_sept,
           df_oct,df_nov,df_dec], axis=0)

In [4]:
df_chicago = df_chicago.reset_index(drop = True)

In [5]:
df_chicago.columns = df_chicago.columns.str.strip().str.replace(' ','_')

In [6]:
df_chicago

,Trip_ID,Taxi_ID,Trip_Start_Timestamp,Trip_End_Timestamp,Trip_Seconds,Trip_Miles,Pickup_Census_Tract,Dropoff_Census_Tract,Pickup_Community_Area,Dropoff_Community_Area,...,Trip_Total,Payment_Type,Company,Pickup_Centroid_Latitude,Pickup_Centroid_Longitude,Pickup_Centroid_Location,Dropoff_Centroid_Latitude,Dropoff_Centroid_Longitude,Dropoff_Centroid__Location,Community_Areas
0,eda829a425ca1da13e1130c700c876881e26ff9a,b47c583b142d75b42882975eaab19c6cb98d8268601657...,01/01/2013 12:00:00 AM,01/01/2013 12:15:00 AM,600.0,3.0,NaN,NaN,NaN,NaN,...,9.65,Cash,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0c2b3705c9748a5949bf5b7d727b2d1f2e18805f,c2280976049b22e58ce53a17263114616be76981b9ac56...,01/01/2013 12:00:00 AM,01/01/2013 12:30:00 AM,1320.0,12.3,NaN,NaN,NaN,NaN,...,26.25,Cash,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,c15dc571c96c36e44bc4ed50f40330e9f0a21650,294ae9e2f433bb460731f9199b1837de3cf88ad987a42b...,01/01/2013 12:00:00 AM,01/01/2013 12:30:00 AM,1320.0,6.3,NaN,NaN,NaN,NaN,...,19.45,Credit Card,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3c979de8d901f317228a40673c3923d72104b92c,2db2ec3555e44930a5d41596cb7935af41c30c30381672...,01/01/2013 12:00:00 AM,01/01/2013 01:30:00 AM,5520.0,88.8,1.703106e+10,NaN,6.0,NaN,...,317.81,Credit Card,NaN,41.942585,-87.656644,POINT (-87.6566440918 41.9425851797),NaN,NaN,NaN,57.0
4,27ad87f629bf14fa3cb894daad514cdad4736f9c,4b38941e0745acdeefe630832a438a59fdaac78640f68a...,01/01/2013 12:00:00 AM,01/01/2013 12:15:00 AM,900.0,2.7,NaN,NaN,28.0,8.0,...,11.45,Cash,NaN,41.874005,-87.663518,POINT (-87.6635175498 41.874005383),41.899602,-87.633308,POINT (-87.6333080367 41.899602111),29.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27217711,2520e0373a96d517bfdebf51df22d1cefa0ac2c3,c7475fec1fa338d525948b60cc20c8a47905a257c68ef8...,12/31/2013 11:45:00 PM,01/01/2014 12:00:00 AM,1141.0,4.4,1.703132e+10,1.703124e+10,32.0,24.0,...,14.55,Cash,American United,41.884987,-87.620993,POINT (-87.6209929134 41.8849871918),41.912364,-87.675063,POINT (-87.6750627566 41.9123643542),38.0
27217712,071675ad64c5cc7134e0d6350f5ad7f9f348bfa8,55af2e70fd4624a43fea70121974c54db44c8e7582ce3d...,12/31/2013 11:45:00 PM,01/01/2014 12:00:00 AM,600.0,0.0,NaN,NaN,NaN,NaN,...,8.45,Cash,Blue Ribbon Taxi Association Inc.,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27217713,5d465f7da1d8c2ff737805adce665d6c7cd9187c,bf89158c52389250e552ac20d9bac0ae9d1e6d0d20e630...,12/31/2013 11:45:00 PM,12/31/2013 11:45:00 PM,NaN,0.0,NaN,NaN,NaN,NaN,...,23.06,Credit Card,Chicago Elite Cab Corp. (Chicago Carriag,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27217714,370b53762ce873bda17547e4eede9213666850ef,b80ea81be262893dbf5c3321e311e0d5a3e475239dabfe...,12/31/2013 11:45:00 PM,12/31/2013 11:45:00 PM,NaN,0.0,NaN,NaN,NaN,NaN,...,9.17,Credit Card,Chicago Elite Cab Corp. (Chicago Carriag,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27217715,1a909d9561676b5b9912ad3f3d974fb8ecb86173,f20c9c5845dab1e51799b959d378c102763d4b31d738da...,12/31/2013 11:45:00 PM,01/01/2014 12:00:00 AM,240.0,0.0,NaN,NaN,NaN,NaN,...,8.34,Credit Card,Chicago Elite Cab Corp. (Chicago Carriag,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
df_chicago.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27217716 entries, 0 to 27217715
Data columns (total 24 columns):
 #   Column                      Dtype
---  ------                      -----
 0   Trip_ID                     object
 1   Taxi_ID                     object
 2   Trip_Start_Timestamp        object
 3   Trip_End_Timestamp          object
 4   Trip_Seconds                float64
 5   Trip_Miles                  float64
 6   Pickup_Census_Tract         float64
 7   Dropoff_Census_Tract        float64
 8   Pickup_Community_Area       float64
 9   Dropoff_Community_Area      float64
 10  Fare                        float64
 11  Tips                        float64
 12  Tolls                       float64
 13  Extras                      float64
 14  Trip_Total                  float64
 15  Payment_Type                object
 16  Company                     object
 17  Pickup_Centroid_Latitude    float64
 18  Pickup_Centroid_Longitude   float64
 19  Pickup_Centroid_Location    object
 20  Dropoff_Centroid_Latitude   float64
 21  Dropoff_Centroid_Longitude  float64
 22  Dropoff_Centroid__Location  object
 23  Community_Areas             float64
dtypes: float64(16), object(8)
memory usage: 4.9+ GB

In [8]:
df_chicago['Trip_Start_Timestamp'] = pd.to_datetime(df_chicago['Trip_Start_Timestamp'])
df_chicago['Trip_End_Timestamp'] = pd.to_datetime(df_chicago['Trip_End_Timestamp'])

In [9]:
negative_miles = (df_chicago['Trip_Miles'] <= 0).sum()
negative_seconds = (df_chicago['Trip_Seconds'] < 60).sum()
print(negative_miles)
print(negative_seconds)

12049064
1353120

In [10]:
df_chicago = df_chicago[df_chicago['Trip_Miles'] > 0]
df_chicago = df_chicago[df_chicago['Trip_Seconds'] >= 0]

In [11]:
df_chicago.reset_index(drop = True)

,Trip_ID,Taxi_ID,Trip_Start_Timestamp,Trip_End_Timestamp,Trip_Seconds,Trip_Miles,Pickup_Census_Tract,Dropoff_Census_Tract,Pickup_Community_Area,Dropoff_Community_Area,...,Trip_Total,Payment_Type,Company,Pickup_Centroid_Latitude,Pickup_Centroid_Longitude,Pickup_Centroid_Location,Dropoff_Centroid_Latitude,Dropoff_Centroid_Longitude,Dropoff_Centroid__Location,Community_Areas
0,eda829a425ca1da13e1130c700c876881e26ff9a,b47c583b142d75b42882975eaab19c6cb98d8268601657...,2013-01-01 00:00:00,2013-01-01 00:15:00,600.0,3.0,NaN,NaN,NaN,NaN,...,9.65,Cash,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0c2b3705c9748a5949bf5b7d727b2d1f2e18805f,c2280976049b22e58ce53a17263114616be76981b9ac56...,2013-01-01 00:00:00,2013-01-01 00:30:00,1320.0,12.3,NaN,NaN,NaN,NaN,...,26.25,Cash,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,c15dc571c96c36e44bc4ed50f40330e9f0a21650,294ae9e2f433bb460731f9199b1837de3cf88ad987a42b...,2013-01-01 00:00:00,2013-01-01 00:30:00,1320.0,6.3,NaN,NaN,NaN,NaN,...,19.45,Credit Card,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3c979de8d901f317228a40673c3923d72104b92c,2db2ec3555e44930a5d41596cb7935af41c30c30381672...,2013-01-01 00:00:00,2013-01-01 01:30:00,5520.0,88.8,1.703106e+10,NaN,6.0,NaN,...,317.81,Credit Card,NaN,41.942585,-87.656644,POINT (-87.6566440918 41.9425851797),NaN,NaN,NaN,57.0
4,27ad87f629bf14fa3cb894daad514cdad4736f9c,4b38941e0745acdeefe630832a438a59fdaac78640f68a...,2013-01-01 00:00:00,2013-01-01 00:15:00,900.0,2.7,NaN,NaN,28.0,8.0,...,11.45,Cash,NaN,41.874005,-87.663518,POINT (-87.6635175498 41.874005383),41.899602,-87.633308,POINT (-87.6333080367 41.899602111),29.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15166767,a155865e7578ddd52ed77443c6fed7f981c694b1,cc33cdc1816a9ba9822dd033062f8d414cac183bbfa7fc...,2013-12-31 23:45:00,2013-12-31 23:45:00,536.0,1.6,1.703106e+10,1.703103e+10,6.0,3.0,...,9.85,Credit Card,American United,41.941556,-87.666289,POINT (-87.6662888874 41.941555829),41.965446,-87.663196,POINT (-87.6631958495 41.9654457842),57.0
15166768,35a5fe3a96ad453a9276112136c934a87379e8a5,341cead8979074196f3231099ef811c4e905d7031dd6d7...,2013-12-31 23:45:00,2014-01-01 00:15:00,1952.0,8.5,NaN,NaN,28.0,6.0,...,23.45,Cash,American United,41.874005,-87.663518,POINT (-87.6635175498 41.874005383),41.944227,-87.655998,POINT (-87.6559981815 41.9442266014),29.0
15166769,f6fa0574a62cab2fec2c9ea2cc075f8ff6ee19e5,c01573d08b208b89c0fdf054d7bc2820fe2abb9d326a80...,2013-12-31 23:45:00,2013-12-31 23:45:00,262.0,0.9,1.703132e+10,1.703108e+10,32.0,8.0,...,7.25,Cash,American United,41.884987,-87.620993,POINT (-87.6209929134 41.8849871918),41.898332,-87.620763,POINT (-87.6207628651 41.8983317935),38.0
15166770,de95a68aae83de22d19a7999111f249e90eae812,5866e731fed5c82556c87a73b3ec2e19dd13d4cdc46a34...,2013-12-31 23:45:00,2013-12-31 23:45:00,352.0,0.7,1.703106e+10,1.703106e+10,6.0,6.0,...,7.05,Credit Card,American United,41.942577,-87.647079,POINT (-87.6470785093 41.942577185),41.934540,-87.643023,POINT (-87.6430228044 41.93453971580001),57.0
15166771,2520e0373a96d517bfdebf51df22d1cefa0ac2c3,c7475fec1fa338d525948b60cc20c8a47905a257c68ef8...,2013-12-31 23:45:00,2014-01-01 00:00:00,1141.0,4.4,1.703132e+10,1.703124e+10,32.0,24.0,...,14.55,Cash,American United,41.884987,-87.620993,POINT (-87.6209929134 41.8849871918),41.912364,-87.675063,POINT (-87.6750627566 41.9123643542),38.0

In [12]:
df_chicago.duplicated(subset=['Taxi_ID','Trip_Start_Timestamp']).sum()

1496071

In [13]:
df_chicago.drop_duplicates(subset=['Taxi_ID','Trip_Start_Timestamp'], inplace = True)

In [22]:
df_chicago['date_start'] = df_chicago['Trip_Start_Timestamp'].dt.date
df_chicago['date_start'] = pd.to_datetime(df_chicago['date_start'])
#df_chicago['time_start'] =df_chicago['Trip_Start_Timestamp'].dt.time
#df_chicago['time_end'] =df_chicago['Trip_End_Timestamp'].dt.time

In [47]:
overlap = df_chicago.groupby('Taxi_ID').apply(
    lambda group: group[
        (group['Trip_Start_Timestamp'].lt(group['Trip_End_Timestamp'].shift(-1))) &
        (group['Trip_End_Timestamp'].gt(group['Trip_Start_Timestamp'].shift(-1)))
    ]
)
overlap

                                                                                              Trip_ID  \
Taxi_ID
0044e6c0d091476299b99345501f756b23632a96cbaf40e... 24104795  7f21d680ed72a1d91fe751b41eb0d61e5ec242f9
008c43f04857eb09949b8ce05458d3fc8848dfd460d9253... 2736336   6b6fe52de9ba4459f049d14b1286098449b58e1f
                                                   4885669   aa7f5fe5d310aa395baa50aa72aafdd91ca36852
                                                   5622888   625158b7a1bfbd71466c5c9108353c1928a2559f
                                                   6002445   3c287adfa9bd4ea9168a5873f80ec241c9570dda
...                                                                                               ...
ffc2a618ad19a63fa5e9ce8b1bd68656172b2eac505f0a2... 24901707  4898de351822515f6f557ef0e2923d5612992827
                                                   25534039  1aa13e5bc1b1f929d7d33efd468d6386c60dd457
                                                   25567639  fd844638b147cdcd8d3136bc1fad5b93e3cdce66
                                                   26500530  755d9a49965f24e2e0925f9174dfd058dae3cd74
                                                   26575637  6cfbec0aa7be072faef40f78d152d119996249bc

                                                                                                       Taxi_ID  \
Taxi_ID
0044e6c0d091476299b99345501f756b23632a96cbaf40e... 24104795  0044e6c0d091476299b99345501f756b23632a96cbaf40...
008c43f04857eb09949b8ce05458d3fc8848dfd460d9253... 2736336   008c43f04857eb09949b8ce05458d3fc8848dfd460d925...
                                                   4885669   008c43f04857eb09949b8ce05458d3fc8848dfd460d925...
                                                   5622888   008c43f04857eb09949b8ce05458d3fc8848dfd460d925...
                                                   6002445   008c43f04857eb09949b8ce05458d3fc8848dfd460d925...
...                                                                                                        ...
ffc2a618ad19a63fa5e9ce8b1bd68656172b2eac505f0a2... 24901707  ffc2a618ad19a63fa5e9ce8b1bd68656172b2eac505f0a...
                                                   25534039  ffc2a618ad19a63fa5e9ce8b1bd68656172b2eac505f0a...
                                                   25567639  ffc2a618ad19a63fa5e9ce8b1bd68656172b2eac505f0a...
                                                   26500530  ffc2a618ad19a63fa5e9ce8b1bd68656172b2eac505f0a...
                                                   26575637  ffc2a618ad19a63fa5e9ce8b1bd68656172b2eac505f0a...

                                                            Trip_Start_Timestamp  \
Taxi_ID
0044e6c0d091476299b99345501f756b23632a96cbaf40e... 24104795  2013-11-24 00:30:00
008c43f04857eb09949b8ce05458d3fc8848dfd460d9253... 2736336   2013-02-19 15:30:00
                                                   4885669   2013-03-20 11:30:00
                                                   5622888   2013-03-31 07:00:00
                                                   6002445   2013-04-06 10:00:00
...                                                                          ...
ffc2a618ad19a63fa5e9ce8b1bd68656172b2eac505f0a2... 24901707  2013-12-05 06:00:00
                                                   25534039  2013-12-11 14:45:00
                                                   25567639  2013-12-11 20:30:00
                                                   26500530  2013-12-21 06:30:00
                                                   26575637  2013-12-22 00:15:00

                                                             Trip_End_Timestamp  \
Taxi_ID
0044e6c0d091476299b99345501f756b23632a96cbaf40e... 24104795 2013-11-24 01:00:00
008c43f04857eb09949b8ce05458d3fc8848dfd460d9253... 2736336  2013-02-20 00:00:00
                                                   4885669  2013-03-21 00:00:00
                                                   5622888  2013-04-01 00:00:00
                                                   6002445  2013-04-07 00:00:00
...                                                                         ...
ffc2a618ad19a63fa5e9ce8b1bd68656172b2eac505f0a2... 24901707 2013-12-05 06:45:00
                                                   25534039 2013-12-11 15:15:00
                                                   25567639 2013-12-11 21:00:00
                                                   26500530 2013-12-21 07:00:00
                                                   26575637 2013-12-22 00:45:00

                                                             Trip_Seconds  \
Taxi_ID
0044e6c0d091476299b99345501f756b23632a96cbaf40e... 24104795        1200.0
008c43f04857eb09949b8ce05458d3fc8848dfd460d9253... 2736336        30360.0
                                                   4885669        44940.0
                                                   5622888        61200.0
                                                   6002445        50820.0
...                                                                   ...
ffc2a618ad19a63fa5e9ce8b1bd68656172b2eac505f0a2... 24901707        2040.0
                                                   25534039        1560.0
                                                   25567639        1380.0
                                                   26500530        1200.0
                                                   26575637        1620.0

                                                             Trip_Miles  \
Taxi_ID
0044e6c0d091476299b99345501f756b23632a96cbaf40e... 24104795         6.8
008c43f04857eb09949b8ce05458d3fc8848dfd460d9253... 2736336          1.8
                                                   4885669         17.9
                                                   5622888          2.2
                                                   6002445          5.7
...                                                                 ...
ffc2a618ad19a63fa5e9ce8b1bd68656172b2eac505f0a2... 24901707        19.6
                                                   25534039        33.4
                                                   25567639        13.8
                                                   26500530         6.9
                                                   26575637        15.0

                                                             Pickup_Census_Tract  \
Taxi_ID
0044e6c0d091476299b99345501f756b23632a96cbaf40e... 24104795                  NaN
008c43f04857eb09949b8ce05458d3fc8848dfd460d9253... 2736336                   NaN
                                                   4885669                   NaN
                                                   5622888                   NaN
                                                   6002445                   NaN
...                                                                          ...
ffc2a618ad19a63fa5e9ce8b1bd68656172b2eac505f0a2... 24901707         1.703128e+10
                                                   25534039         1.703183e+10
                                                   25567639                  NaN
                                                   26500530                  NaN
                                                   26575637                  NaN

                                                             Dropoff_Census_Tract  \
Taxi_ID
0044e6c0d091476299b99345501f756b23632a96cbaf40e... 24104795                   NaN
008c43f04857eb09949b8ce05458d3fc8848dfd460d9253... 2736336                    NaN
                                                   4885669                    NaN
                                                   5622888                    NaN
                                                   6002445                    NaN
...                                                                           ...
ffc2a618ad19a63fa5e9ce8b1bd68656172b2eac505f0a2... 24901707          1.703133e+10
                                                   25534039          1.703198e+10
                                                   25567639                   NaN
                                                   26500530                   NaN
                                                   26575637                   NaN

                                                             Pickup_Community_Area  \
Taxi_ID
0044e6c0d091476299b99345501f756b23632a96cbaf40e... 24104795                   22.0
008c43f04857eb09949b8ce05458d3fc8848dfd460d9253... 2736336                     NaN
                                                   4885669                     NaN
                                                   5622888                     NaN
                                                   6002445                     NaN
...                                                                            ...
ffc2a618ad19a63fa5e9ce8b1bd68656172b2eac505f0a2... 24901707                   28.0
                                                   25534039                   28.0
                                                   25567639                   56.0
                                                   26500530                    3.0
                                                   26575637                    6.0

                                                             Dropoff_Community_Area  \
Taxi_ID
0044e6c0d091476299b99345501f756b23632a96cbaf40e... 24104795                     2.0
008c43f04857eb09949b8ce05458d3fc8848dfd460d9253... 2736336                      NaN
                                                   4885669                      NaN
                                                   5622888                      NaN
                                                   6002445                      NaN
...                                                                             ...
ffc2a618ad19a63fa5e9ce8b1bd68656172b2eac505f0a2... 24901707                    33.0
                                                   25534039                    76.0
                                                   25567639                    41.0
                                                   26500530                    15.0
                                                   26575637                     NaN

                                                             ...  \
Taxi_ID                                                      ...
0044e6c0d091476299b99345501f756b23632a96cbaf40e... 24104795  ...
008c43f04857eb09949b8ce05458d3fc8848dfd460d9253... 2736336   ...
                                                   4885669   ...
                                                   5622888   ...
                                                   6002445   ...
...                                                          ...
ffc2a618ad19a63fa5e9ce8b1bd68656172b2eac505f0a2... 24901707  ...
                                                   25534039  ...
                                                   25567639  ...
                                                   26500530  ...
                                                   26575637  ...

                                                             Payment_Type  \
Taxi_ID
0044e6c0d091476299b99345501f756b23632a96cbaf40e... 24104795          Cash
008c43f04857eb09949b8ce05458d3fc8848dfd460d9253... 2736336           Cash
                                                   4885669           Cash
                                                   5622888           Cash
                                                   6002445           Cash
...                                                                   ...
ffc2a618ad19a63fa5e9ce8b1bd68656172b2eac505f0a2... 24901707          Cash
                                                   25534039          Cash
                                                   25567639          Cash
                                                   26500530          Cash
                                                   26575637          Cash

                                                             Company  \
Taxi_ID
0044e6c0d091476299b99345501f756b23632a96cbaf40e... 24104795      NaN
008c43f04857eb09949b8ce05458d3fc8848dfd460d9253... 2736336       NaN
                                                   4885669       NaN
                                                   5622888       NaN
                                                   6002445       NaN
...                                                              ...
ffc2a618ad19a63fa5e9ce8b1bd68656172b2eac505f0a2... 24901707      NaN
                                                   25534039      NaN
                                                   25567639      NaN
                                                   26500530      NaN
                                                   26575637      NaN

                                                             Pickup_Centroid_Latitude  \
Taxi_ID
0044e6c0d091476299b99345501f756b23632a96cbaf40e... 24104795                 41.922761
008c43f04857eb09949b8ce05458d3fc8848dfd460d9253... 2736336                        NaN
                                                   4885669                        NaN
                                                   5622888                        NaN
                                                   6002445                        NaN
...                                                                               ...
ffc2a618ad19a63fa5e9ce8b1bd68656172b2eac505f0a2... 24901707                 41.879255
                                                   25534039                 41.885281
                                                   25567639                 41.792592
                                                   26500530                 41.965812
                                                   26575637                 41.944227

                                                             Pickup_Centroid_Longitude  \
Taxi_ID
0044e6c0d091476299b99345501f756b23632a96cbaf40e... 24104795                 -87.699155
008c43f04857eb09949b8ce05458d3fc8848dfd460d9253... 2736336                         NaN
                                                   4885669                         NaN
                                                   5622888                         NaN
                                                   6002445                         NaN
...                                                                                ...
ffc2a618ad19a63fa5e9ce8b1bd68656172b2eac505f0a2... 24901707                 -87.642649
                                                   25534039                 -87.657233
                                                   25567639                 -87.769615
                                                   26500530                 -87.655879
                                                   26575637                 -87.655998

                                                                             Pickup_Centroid_Location  \
Taxi_ID
0044e6c0d091476299b99345501f756b23632a96cbaf40e... 24104795  POINT (-87.69915534320002 41.9227606205)
008c43f04857eb09949b8ce05458d3fc8848dfd460d9253... 2736336                                        NaN
                                                   4885669                                        NaN
                                                   5622888                                        NaN
                                                   6002445                                        NaN
...                                                                                               ...
ffc2a618ad19a63fa5e9ce8b1bd68656172b2eac505f0a2... 24901707       POINT (-87.642648998 41.8792550844)
                                                   25534039      POINT (-87.6572331997 41.8852813201)
                                                   25567639      POINT (-87.7696154528 41.7925923603)
                                                   26500530        POINT (-87.6558787862 41.96581197)
                                                   26575637      POINT (-87.6559981815 41.9442266014)

                                                            Dropoff_Centroid_Latitude  \
Taxi_ID
0044e6c0d091476299b99345501f756b23632a96cbaf40e... 24104795                 42.001571
008c43f04857eb09949b8ce05458d3fc8848dfd460d9253... 2736336                        NaN
                                                   4885669                        NaN
                                                   5622888                        NaN
                                                   6002445                        NaN
...                                                                               ...
ffc2a618ad19a63fa5e9ce8b1bd68656172b2eac505f0a2... 24901707                 41.859350
                                                   25534039                 41.979071
                                                   25567639                 41.794090
                                                   26500530                 41.954028
                                                   26575637                       NaN

                                                            Dropoff_Centroid_Longitude  \
Taxi_ID
0044e6c0d091476299b99345501f756b23632a96cbaf40e... 24104795                 -87.695013
008c43f04857eb09949b8ce05458d3fc8848dfd460d9253... 2736336                         NaN
                                                   4885669                         NaN
                                                   5622888                         NaN
                                                   6002445                         NaN
...                                                                                ...
ffc2a618ad19a63fa5e9ce8b1bd68656172b2eac505f0a2... 24901707                 -87.617358
                                                   25534039                 -87.903040
                                                   25567639                 -87.592311
                                                   26500530                 -87.763399
                                                   26575637                        NaN

                                                                       Dropoff_Centroid__Location  \
Taxi_ID
0044e6c0d091476299b99345501f756b23632a96cbaf40e... 24104795   POINT (-87.6950125892 42.001571027)
008c43f04857eb09949b8ce05458d3fc8848dfd460d9253... 2736336                                    NaN
                                                   4885669                                    NaN
                                                   5622888                                    NaN
                                                   6002445                                    NaN
...                                                                                           ...
ffc2a618ad19a63fa5e9ce8b1bd68656172b2eac505f0a2... 24901707   POINT (-87.6173580061 41.859349715)
                                                   25534039  POINT (-87.9030396611 41.9790708201)
                                                   25567639    POINT (-87.592310855 41.794090253)
                                                   26500530  POINT (-87.7633990316 41.9540276487)
                                                   26575637                                   NaN

                                                             Community_Areas  \
Taxi_ID
0044e6c0d091476299b99345501f756b23632a96cbaf40e... 24104795             23.0
008c43f04857eb09949b8ce05458d3fc8848dfd460d9253... 2736336               NaN
                                                   4885669               NaN
                                                   5622888               NaN

In [46]:
overlap.head(20)

                                                                                              Trip_ID  \
Taxi_ID
001330b81e23412049f9c3eff5b6e972a91afe59c9aa36e... 13205654  7797e40db82db8850c092c84b3f2c3b8fec632b1
                                                   13291986  0ef29da82cdec5963572366221b0d0ea8bfaa222
                                                   13301540  dc225e94e83b162bf2426e0bd46a3990d7947ffb
                                                   13309182  34a3a98a1720322c6f4a28bfb1a44ede81cf0dff
                                                   13391564  206b8afcb15e5d114f379945bef8ab060e92ef2d
                                                   13431226  5c8b9cb00e00ed45e85aa5513ace5aba43ff118d
                                                   13433835  9b8007d55f7b69838b8b53f999aab85808725e8d
                                                   13466817  15c18edbb8869198aa125718070219c527b44309
                                                   13609585  032b1d7e892e6f295626bee0cb64c90a433106e4
                                                   13673355  f92800b1a2ad9ffcbd64c1438413401a1bb18534
                                                   13748739  7e8800241452294b88286848d03b8495fa9cbbb2
                                                   13749635  120a9e9a13d6dc4bc49a565a66f32e90da4f06a4
                                                   13755702  29aa4ac0a94e61039623560248879e2316a740be
                                                   13800511  c20b7ab78d70cf36621fbe64d21eff20d5cc4362
                                                   13884810  3bf26977c3d75c9de90f96906ec7cad6c686a776
                                                   13892610  ea4e63373707db2b99295bf04bbdd18d1e0c3424
                                                   13897397  2a11d6c014daa6d14afbdbc6126c8feed2c9ce69
                                                   13898802  b5f3caedbac89061e27ab98621e829fbdfc700f9
                                                   13977010  b881d94b06cf67ec08dce1b8b007f1f91f1b8031
                                                   13988476  657e1aa2b0785620f070e07e9a4875a4c784bc4a

                                                                                                       Taxi_ID  \
Taxi_ID
001330b81e23412049f9c3eff5b6e972a91afe59c9aa36e... 13205654  001330b81e23412049f9c3eff5b6e972a91afe59c9aa36...
                                                   13291986  001330b81e23412049f9c3eff5b6e972a91afe59c9aa36...
                                                   13301540  001330b81e23412049f9c3eff5b6e972a91afe59c9aa36...
                                                   13309182  001330b81e23412049f9c3eff5b6e972a91afe59c9aa36...
                                                   13391564  001330b81e23412049f9c3eff5b6e972a91afe59c9aa36...
                                                   13431226  001330b81e23412049f9c3eff5b6e972a91afe59c9aa36...
                                                   13433835  001330b81e23412049f9c3eff5b6e972a91afe59c9aa36...
                                                   13466817  001330b81e23412049f9c3eff5b6e972a91afe59c9aa36...
                                                   13609585  001330b81e23412049f9c3eff5b6e972a91afe59c9aa36...
                                                   13673355  001330b81e23412049f9c3eff5b6e972a91afe59c9aa36...
                                                   13748739  001330b81e23412049f9c3eff5b6e972a91afe59c9aa36...
                                                   13749635  001330b81e23412049f9c3eff5b6e972a91afe59c9aa36...
                                                   13755702  001330b81e23412049f9c3eff5b6e972a91afe59c9aa36...
                                                   13800511  001330b81e23412049f9c3eff5b6e972a91afe59c9aa36...
                                                   13884810  001330b81e23412049f9c3eff5b6e972a91afe59c9aa36...
                                                   13892610  001330b81e23412049f9c3eff5b6e972a91afe59c9aa36...
                                                   13897397  001330b81e23412049f9c3eff5b6e972a91afe59c9aa36...
                                                   13898802  001330b81e23412049f9c3eff5b6e972a91afe59c9aa36...
                                                   13977010  001330b81e23412049f9c3eff5b6e972a91afe59c9aa36...
                                                   13988476  001330b81e23412049f9c3eff5b6e972a91afe59c9aa36...

                                                            Trip_Start_Timestamp  \
Taxi_ID
001330b81e23412049f9c3eff5b6e972a91afe59c9aa36e... 13205654  2013-07-12 19:45:00
                                                   13291986  2013-07-13 17:30:00
                                                   13301540  2013-07-13 19:15:00
                                                   13309182  2013-07-13 20:30:00
                                                   13391564  2013-07-14 17:45:00
                                                   13431226  2013-07-15 10:15:00
                                                   13433835  2013-07-15 11:00:00
                                                   13466817  2013-07-15 19:45:00
                                                   13609585  2013-07-17 20:00:00
                                                   13673355  2013-07-18 17:00:00
                                                   13748739  2013-07-19 14:15:00
                                                   13749635  2013-07-19 14:30:00
                                                   13755702  2013-07-19 15:45:00
                                                   13800511  2013-07-19 23:00:00
                                                   13884810  2013-07-20 20:15:00
                                                   13892610  2013-07-20 21:30:00
                                                   13897397  2013-07-20 22:15:00
                                                   13898802  2013-07-20 22:30:00
                                                   13977010  2013-07-21 19:15:00
                                                   13988476  2013-07-21 22:30:00

                                                             Trip_End_Timestamp  \
Taxi_ID
001330b81e23412049f9c3eff5b6e972a91afe59c9aa36e... 13205654 2013-07-12 20:00:00
                                                   13291986 2013-07-13 18:00:00
                                                   13301540 2013-07-13 19:30:00
                                                   13309182 2013-07-13 20:45:00
                                                   13391564 2013-07-14 18:00:00
                                                   13431226 2013-07-15 11:00:00
                                                   13433835 2013-07-15 11:15:00
                                                   13466817 2013-07-15 20:15:00
                                                   13609585 2013-07-17 20:45:00
                                                   13673355 2013-07-18 17:15:00
                                                   13748739 2013-07-19 14:30:00
                                                   13749635 2013-07-19 14:45:00
                                                   13755702 2013-07-19 16:00:00
                                                   13800511 2013-07-19 23:15:00
                                                   13884810 2013-07-20 20:30:00
                                                   13892610 2013-07-20 21:45:00
                                                   13897397 2013-07-20 22:30:00
                                                   13898802 2013-07-20 22:45:00
                                                   13977010 2013-07-21 19:45:00
                                                   13988476 2013-07-21 23:00:00

                                                             Trip_Seconds  \
Taxi_ID
001330b81e23412049f9c3eff5b6e972a91afe59c9aa36e... 13205654        1200.0
                                                   13291986        1800.0
                                                   13301540         900.0
                                                   13309182         840.0
                                                   13391564         540.0
                                                   13431226        2340.0
                                                   13433835         360.0
                                                   13466817        1680.0
                                                   13609585        2460.0
                                                   13673355         180.0
                                                   13748739         300.0
                                                   13749635         540.0
                                                   13755702         660.0
                                                   13800511         540.0
                                                   13884810         480.0
                                                   13892610         240.0
                                                   13897397         720.0
                                                   13898802         480.0
                                                   13977010        1680.0
                                                   13988476        1620.0

                                                             Trip_Miles  \
Taxi_ID
001330b81e23412049f9c3eff5b6e972a91afe59c9aa36e... 13205654         3.8
                                                   13291986         3.4
                                                   13301540         3.2
                                                   13309182         4.4
                                                   13391564         1.3
                                                   13431226        17.4
                                                   13433835         1.1
                                                   13466817        18.0
                                                   13609585        17.8
                                                   13673355         1.1
                                                   13748739         0.7
                                                   13749635         1.3
                                                   13755702         2.0
                                                   13800511         1.4
                                                   13884810         1.8
                                                   13892610         0.7
                                                   13897397         2.4
                                                   13898802         1.1
                                                   13977010        18.0
                                                   13988476        18.4

                                                             Pickup_Census_Tract  \
Taxi_ID
001330b81e23412049f9c3eff5b6e972a91afe59c9aa36e... 13205654         1.703108e+10
                                                   13291986         1.703133e+10
                                                   13301540         1.703107e+10
                                                   13309182         1.703107e+10
                                                   13391564         1.703132e+10
                                                   13431226         1.703198e+10
                                                   13433835         1.703108e+10
                                                   13466817         1.703198e+10
                                                   13609585         1.703198e+10
                                                   13673355                  NaN
                                                   13748739         1.703184e+10
                                                   13749635         1.703108e+10
                                                   13755702         1.703184e+10
                                                   13800511         1.703107e+10
                                                   13884810         1.703107e+10
                                                   13892610         1.703107e+10
                                                   13897397         1.703108e+10
                                                   13898802         1.703183e+10
                                                   13977010         1.703198e+10
                                                   13988476         1.703198e+10

                                                             Dropoff_Census_Tract  \
Taxi_ID
001330b81e23412049f9c3eff5b6e972a91afe59c9aa36e... 13205654          1.703124e+10
                                                   13291986          1.703108e+10
                                                   13301540          1.703106e+10
                                                   13309182          1.703184e+10
                                                   13391564          1.703108e+10
                                                   13431226          1.703108e+10
                                                   13433835          1.703184e+10
                                                   13466817          1.703184e+10
                                                   13609585          1.703108e+10
                                                   13673355                   NaN
                                                   13748739          1.703128e+10
                                                   13749635          1.703132e+10
                                                   13755702          1.703107e+10
                                                   13800511          1.703108e+10
                                                   13884810          1.703108e+10
                                                   13892610          1.703106e+10
                                                   13897397          1.703107e+10
                                                   13898802          1.703107e+10
                                                   13977010          1.703132e+10
                                                   13988476          1.703108e+10

                                                             Pickup_Community_Area  \
Taxi_ID
001330b81e23412049f9c3eff5b6e972a91afe59c9aa36e... 13205654                    8.0
                                                   13291986                   33.0
                                                   13301540                    7.0
                                                   13309182                    7.0
                                                   13391564                   32.0
                                                   13431226                   76.0
                                                   13433835                    8.0
                                                   13466817                   76.0
                                                   13609585                   76.0
                                                   13673355                   32.0
                                                   13748739                   32.0
                                                   13749635                    8.0
                                                   13755702                   32.0
                                                   13800511                    7.0
                                                   13884810                    7.0
                                                   13892610                    7.0
                                                   13897397                    8.0
                                                   13898802                    7.0
                                                   13977010                   76.0
                                                   13988476                   76.0

                                                             Dropoff_Community_Area  \
Taxi_ID
001330b81e23412049f9c3eff5b6e972a91afe59c9aa36e... 13205654                    24.0
                                                   13291986                     8.0
                                                   13301540                     6.0
                                                   13309182                    24.0
                                                   13391564                     8.0
                                                   13431226                     8.0
                                                   13433835                    32.0
                                                   13466817                    32.0
                                                   13609585                     8.0
                                                   13673355                    34.0
                                                   13748739                    28.0
                                                   13749635                    32.0
                                                   13755702                     7.0
                                                   13800511                     8.0
                                                   13884810                     8.0
                                                   13892610                     6.0
                                                   13897397                     7.0
                                                   13898802                     7.0
                                                   13977010                    32.0
                                                   13988476                     8.0

                                                             ...  \
Taxi_ID                                                      ...
001330b81e23412049f9c3eff5b6e972a91afe59c9aa36e... 13205654  ...
                                                   13291986  ...
                                                   13301540  ...
                                                   13309182  ...
                                                   13391564  ...
                                                   13431226  ...
                                                   13433835  ...
                                                   13466817  ...
                                                   13609585  ...
                                                   13673355  ...
                                                   13748739  ...
                                                   13749635  ...
                                                   13755702  ...
                                                   13800511  ...
                                                   13884810  ...
                                                   13892610  ...
                                                   13897397  ...
                                                   13898802  ...
                                                   13977010  ...
                                                   13988476  ...

                                                             Payment_Type  \
Taxi_ID
001330b81e23412049f9c3eff5b6e972a91afe59c9aa36e... 13205654   Credit Card
                                                   13291986   Credit Card
                                                   13301540          Cash
                                                   13309182   Credit Card
                                                   13391564          Cash
                                                   13431226   Credit Card

In [56]:
filtered_df = df_chicago[df_chicago['Taxi_ID'] == 'ffc2a618ad19a63fa5e9ce8b1bd68656172b2eac505f0a29b2a5a9460b7035e208d4871b529b55ec38efbb431acb50f123c39db0a8012c1c0a4a2fc20799e3ca']

In [79]:
filtered_df.tail(167)

,Trip_ID,Taxi_ID,Trip_Start_Timestamp,Trip_End_Timestamp,Trip_Seconds,Trip_Miles,Pickup_Census_Tract,Dropoff_Census_Tract,Pickup_Community_Area,Dropoff_Community_Area,...,Payment_Type,Company,Pickup_Centroid_Latitude,Pickup_Centroid_Longitude,Pickup_Centroid_Location,Dropoff_Centroid_Latitude,Dropoff_Centroid_Longitude,Dropoff_Centroid__Location,Community_Areas,date_start
26572849,bd2b9720efdcb860086a9a1b48fb1879f21a9f25,ffc2a618ad19a63fa5e9ce8b1bd68656172b2eac505f0a...,2013-12-21 23:45:00,2013-12-21 23:45:00,780.0,2.7,NaN,NaN,24.0,7.0,...,Cash,NaN,41.901207,-87.676356,POINT (-87.6763559892 41.90120699410001),41.922686,-87.649489,POINT (-87.6494887289 41.9226862843),25.0,2013-12-21
26574226,2b71c9caf2e03c8b2f774729a9b4b9c4c1ce8848,ffc2a618ad19a63fa5e9ce8b1bd68656172b2eac505f0a...,2013-12-22 00:00:00,2013-12-22 00:00:00,120.0,0.3,1.703183e+10,1.703106e+10,6.0,6.0,...,Cash,NaN,41.946295,-87.654298,POINT (-87.6542980837 41.9462945357),41.949221,-87.651970,POINT (-87.6519703953 41.9492209135),57.0,2013-12-22
26575637,6cfbec0aa7be072faef40f78d152d119996249bc,ffc2a618ad19a63fa5e9ce8b1bd68656172b2eac505f0a...,2013-12-22 00:15:00,2013-12-22 00:45:00,1620.0,15.0,NaN,NaN,6.0,NaN,...,Cash,NaN,41.944227,-87.655998,POINT (-87.6559981815 41.9442266014),NaN,NaN,NaN,57.0,2013-12-22
26577011,5abd57388607fb54b600b1333bfbb7d1fd12a7a6,ffc2a618ad19a63fa5e9ce8b1bd68656172b2eac505f0a...,2013-12-22 00:30:00,2013-12-22 00:45:00,1440.0,12.7,NaN,NaN,22.0,41.0,...,Cash,NaN,41.922761,-87.699155,POINT (-87.69915534320002 41.9227606205),41.794090,-87.592311,POINT (-87.592310855 41.794090253),23.0,2013-12-22
26579899,f201c890d2bca4975eff9a1d24f71a49e84d8fef,ffc2a618ad19a63fa5e9ce8b1bd68656172b2eac505f0a...,2013-12-22 01:00:00,2013-12-22 01:15:00,840.0,6.8,NaN,NaN,41.0,60.0,...,Cash,NaN,41.794090,-87.592311,POINT (-87.592310855 41.794090253),41.836150,-87.648788,POINT (-87.6487879519 41.8361501547),8.0,2013-12-22
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27122426,6c1fea11cd0ca15ff48b200656d403919df9fa4a,ffc2a618ad19a63fa5e9ce8b1bd68656172b2eac505f0a...,2013-12-31 01:15:00,2013-12-31 01:15:00,540.0,1.7,1.703183e+10,1.703103e+10,6.0,3.0,...,Cash,NaN,41.946295,-87.654298,POINT (-87.6542980837 41.9462945357),41.962179,-87.645379,POINT (-87.6453787624 41.962178629),57.0,2013-12-31
27123028,98d78699e3ac1c430c99508de13bcab96806742c,ffc2a618ad19a63fa5e9ce8b1bd68656172b2eac505f0a...,2013-12-31 01:30:00,2013-12-31 01:30:00,240.0,1.1,NaN,NaN,6.0,6.0,...,Cash,NaN,41.944227,-87.655998,POINT (-87.6559981815 41.9442266014),41.944227,-87.655998,POINT (-87.6559981815 41.9442266014),57.0,2013-12-31
27123621,79c5b0be33820eb3937a0cf2c47c97cf73b94167,ffc2a618ad19a63fa5e9ce8b1bd68656172b2eac505f0a...,2013-12-31 01:45:00,2013-12-31 02:00:00,600.0,2.8,NaN,NaN,7.0,8.0,...,Cash,NaN,41.922686,-87.649489,POINT (-87.6494887289 41.9226862843),41.899602,-87.633308,POINT (-87.6333080367 41.899602111),68.0,2013-12-31
27124184,359335bf953874574d51396f38e1239f0a4837da,ffc2a618ad19a63fa5e9ce8b1bd68656172b2eac505f0a...,2013-12-31 02:00:00,2013-12-31 02:00:00,120.0,0.5,1.703108e+10,1.703108e+10,8.0,8.0,...,Cash,NaN,41.893216,-87.637844,POINT (-87.6378442095 41.8932163595),41.900266,-87.632109,POINT (-87.6321092196 41.9002656868),37.0,2013-12-31
27141607,31ce92ac228e1d6595c9874b3750ae0804f6ccbd,ffc2a618ad19a63fa5e9ce8b1bd68656172b2eac505f0a...,2013-12-31 12:00:00,2013-12-31 12:00:00,0.0,0.2,NaN,NaN,NaN,NaN,...,Cash,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2013-12-31

In [98]:
#overlap = df_chicago.groupby('Taxi_ID').apply(
 #   lambda group: group[
  #      (group['Trip_Start_Timestamp'].ge(group['Trip_Start_Timestamp'].shift(-1))) &
   #      (group['Trip_Start_Timestamp'].le(group['Trip_End_Timestamp'].shift(-1)))
    #]
#)
#overlap

Empty DataFrame
Columns: [Trip_ID, Taxi_ID, Trip_Start_Timestamp, Trip_End_Timestamp, Trip_Seconds, Trip_Miles, Pickup_Census_Tract, Dropoff_Census_Tract, Pickup_Community_Area, Dropoff_Community_Area, Fare, Tips, Tolls, Extras, Trip_Total, Payment_Type, Company, Pickup_Centroid_Latitude, Pickup_Centroid_Longitude, Pickup_Centroid_Location, Dropoff_Centroid_Latitude, Dropoff_Centroid_Longitude, Dropoff_Centroid__Location, Community_Areas, date_start, time_start, time_end]
Index: []

[0 rows x 27 columns]

In [9]:
len(df_chicago)-len(df_chicago.drop_duplicates(keep=False))

0

In [15]:
df_chicago.duplicated(subset=['Trip_ID']).sum()

0

In [16]:
df_chicago.duplicated(subset=['Taxi_ID','Trip_Start_Timestamp']).sum()

3403338

In [9]:
len(df_chicago['Pickup Centroid Location'])-len(df_chicago['Pickup Centroid Location'].dropna())

4651708